# Generated by Django 5.2.8 on 2026-01-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leaveauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='days_allowed',
            field=models.IntegerField(help_text='Total days allowed per year for this leave type'),
        ),
    ]
