# Generated by Django 5.2.8 on 2026-01-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_alter_leavetype_days_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('is_public', models.BooleanField(default=True, help_text="True if it's a national/public holiday, False if office-specific")),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
